version: "3.8"

services:
  app_dev:
    build:
      context: .
      dockerfile: "./docker/dev.Dockerfile"
    restart: always
    env_file: .env
    ports:
      - 3001:3000
    volumes:
      - .:/app
    networks:
      - tesis

networks:
  tesis:
    name: tesis_net
