version: "3.9"

services:
  app_dev:
    build:
      context: .
      dockerfile: "./docker/dev.Dockerfile"
    env_file: .env
    environment: 
      REACT_APP_SERVER_PORT: 5001
      REACT_APP_SERVER_WEBSOCKET_PORT: 8001
    ports:
      - 3000:3000
    volumes:
      - .:/app
    networks:
      - tesis

networks:
  tesis:
    name: tesis_net_dev
