version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: "./docker/prod.Dockerfile"
    restart: always
    env_file: .env
    ports:
      - 3001:3000
    networks:
      - tesis

networks:
  tesis:
    name: tesis_net
